services:
#    application_core.example:
#        class: Application\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    application_core.admin.school_years:
        class: Application\CoreBundle\Admin\SchoolYearsAdmin
        arguments: [~, Application\CoreBundle\Entity\SchoolYears, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SchoolYears }

    application_core.admin.class_type:
        class: Application\CoreBundle\Admin\ClassTypeAdmin
        arguments: [~, Application\CoreBundle\Entity\ClassType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ClassType }

    application_core.admin.classes:
        class: Application\CoreBundle\Admin\ClassesAdmin
        arguments: [~, Application\CoreBundle\Entity\Classes, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Classes }
