<?php

namespace Application\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClassTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassTypeRepository extends EntityRepository
{
}
