<?php

namespace Application\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolYearsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearsRepository extends EntityRepository
{
}
